[package]
name = "fd-passing-examples"
version = "0.0.1"
authors = ["David Pineau <dav.pineau@gmail.com>", "Guillaume Gomez <guillaume1.gomez@gmail.com>"]

[dependencies]
fd-passing = { path = "../" }
libc = "0.2"
tempdir = "0.3.5"

[[bin]]
name = "simple"
path = "./simple.rs"
